### ISSUE TITLE
Multiple indicators with the same name appear when trying to add an indicator (and the nr increases)

### ISSUE THREAD

**Issue by vaidab** [freqtrade/frequi#1388] opened 2023-07-26 12:06 UTC
**FreqUI Version**

- Version of freqUI: 0.9.5
- version of freqtrade: docker-2023.7.dev-68741239

**Describe the bug**
I'm using an indicator that shows ATR and I have a multiplier over it:
<img width="557" alt="Screenshot 2023-07-26 at 15 03 03" src="https://github.com/freqtrade/frequi/assets/19855026/0e434078-8b71-4744-8f7e-9a261d7136a5">
In main plot I see a lot of "long_atr-long_mult" indicators (10):
<img width="538" alt="Screenshot 2023-07-26 at 15 01 16" src="https://github.com/freqtrade/frequi/assets/19855026/67c62366-b8fe-494b-8aa9-1ad50701fe0e">
If I go to ATR again, I see it's greyed out:
<img width="558" alt="Screenshot 2023-07-26 at 15 03 54" src="https://github.com/freqtrade/frequi/assets/19855026/361fc60b-8689-4707-8b57-4d69baf73952">
I press ok, I click the gear button, go to ATR and long_atr is clickable again:
<img width="540" alt="Screenshot 2023-07-26 at 15 04 33" src="https://github.com/freqtrade/frequi/assets/19855026/a495b972-60ba-4d49-8910-3a72eff2b50a">
Now there are more indicators with the exact same name (12):
<img width="507" alt="Screenshot 2023-07-26 at 15 05 02" src="https://github.com/freqtrade/frequi/assets/19855026/5e9191cb-0550-49dd-9685-d51a04882d68">
And if I go to ATR it's again greyed out.

**Plot code**

```
{
  "main_plot": {},
  "subplots": {
    "ATR": {
      "long_atr": {
        "color": "#00f900",
        "type": "line",
        "fill_to": "long_mult"
      }
    }
  }
}

```
**Expected behavior**
Not to show multiple indicators with the same name.

**Desktop:**
 - OS: MacOSX

 - Browser Safari 
 - Version 16.5.2

**Comment by vaidab** [comment] 2023-07-26 12:34
From pair_history: (Sources -> backtest -> XHRs -> pair_history -> Response)

 ```
   "columns": [
        "date",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "date_1d",
        "age_filter_ok_1d",
        "live_data_ok",
        "long_atr",
        "long_mult",
        "enter_long",
        "short_atr",
        "short_mult",
        "enter_short",
        "exit_long",
        "exit_short",
        "__date_ts",
        "_enter_long_signal_close",
        "_exit_long_signal_close",
        "_enter_short_signal_close",
        "_exit_short_signal_close"
    ],

```


Strategy part:
  ```
  plot_config = {
        "main_plot": {
        },
        "subplots": {
            'ATR': {
                "long_atr": {
                    "color": "#00f900",
                    "type": "line",
                    "fill_to": "long_mult"
                }
            },
            "filters": {
                "age_filter_ok_1d": {
                    "color": "#ff9300",
                    "type": "scatter"
                 },
                 "live_data_ok": {
                     "color": "#1dab8a",
                     "type": "line"
                  }
            }
        }
                # f'long_atr_{long_atr.value}': {'color': 'violet'},
                # f'long_atr_{long_atr.value}_mult_{long_mult.value}': {'color': 'blue'},
                # f'short_atr_{short_atr.value}': {'color': 'blood'},
                # f'short_atr_{short_atr.value}_mult_{short_mult.value}': {'color': 'red'},
    }
```

**Comment by xmatthias** [comment] 2023-07-26 13:57
it's quite interesting that the actual string shown `long_atr-long_mult` is not part of the columns - so for now (without looking at the code) - i don't really understand why this is happening.

Will take a look though - will let you know if i need some more info.

**Comment by perkmeister** [comment] 2023-07-27 01:19
Would (does?) the alterative way using `plot_config(self):` work?
https://www.freqtrade.io/en/stable/plotting/#advanced-plot-configuration

**Comment by vaidab** [comment] 2023-07-27 03:56
I get this:

> 2023-07-27 03:52:23,472 - freqtrade.plot.plotting - WARNING - Indicator long_atr has unknown plot trace kind line, assuming "scatter".
> 2023-07-27 03:52:23,472 - freqtrade - ERROR - Fatal exception!
> Traceback (most recent call last):
>   File "/freqtrade/freqtrade/main.py", line 42, in main
>     return_code = args['func'](args)
>                   ^^^^^^^^^^^^^^^^^^
>   File "/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
>     load_and_plot_trades(config)
>   File "/freqtrade/freqtrade/plot/plotting.py", line 656, in load_and_plot_trades
>     fig = generate_candlestick_graph(
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/freqtrade/freqtrade/plot/plotting.py", line 521, in generate_candlestick_graph
>     fig = add_indicators(fig=fig, row=row, indicators=sub_config,
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/freqtrade/freqtrade/plot/plotting.py", line 131, in add_indicators
>     trace = plot_kinds[plot_type](**kwargs)
>             ~~~~~~~~~~^^^^^^^^^^^
> KeyError: 'line'

**Comment by xmatthias** [comment] 2023-07-27 05:25
Nice find - it's caused by the "fill_to" calculation, which caused additional columns to be added.

should be fixed in main ... will do a release later this week.

**Closed** 2023-07-27 05:24 UTC
Labels: bug
